const $=id=>document.getElementById(id);
const state={topic:null,activity:null,session:null,tick:null,activityStart:0,currentItems:[]};
const ACTS=[
 {id:'flashcards',title:'1. Flashcards',desc:'Deutsch ↔ Spanisch sehen und merken'},
 {id:'mc-de-es',title:'2. Multiple Choice',desc:'Deutsch → Spanisch wählen'},
 {id:'mc-es-de',title:'3. Umgekehrt',desc:'Spanisch → Deutsch wählen'},
 {id:'write-de',title:'4. Schreiben',desc:'Spanisch lesen, Deutsch schreiben'},
 {id:'write-es',title:'5. Übersetzen',desc:'Deutsch lesen, Spanisch schreiben'},
 {id:'match',title:'6. Zuordnen',desc:'Paare verbinden'},
 {id:'cloze',title:'7. Lückensätze',desc:'Wort im Satz ergänzen'},
 {id:'free',title:'8. Freier Text',desc:'Mit dem Wortschatz frei schreiben'}
];
function norm(s){return (s||'').toString().trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[.!?¿¡,;]/g,'').replace(/^(der|die|das|el|la|los|las)\s+/,'').replace(/\s+/g,' ')}
function nowISO(){return new Date().toISOString()}function pad(n){return String(n).padStart(2,'0')}function elapsed(){return state.session?Math.floor((Date.now()-state.session.startedMs)/1000):0}function fmt(sec){return pad(Math.floor(sec/60))+':'+pad(sec%60)}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function sampleWords(){return shuffle(state.topic.words).slice(0,Math.min(8,state.topic.words.length))}
function init(){renderTopics();renderMenu();$('saveProfileBtn').onclick=saveProfile;$('resetBtn').onclick=reset;$('changeTopicBtn').onclick=changeTopic;$('finishBtn').onclick=finish;$('backMenuBtn').onclick=showMenu;$('backMenuBtn2').onclick=showMenu;$('checkBtn').onclick=check;$('againBtn').onclick=()=>openActivity(state.activity.id);restoreDraft();}
function saveProfile(){if(!$('studentName').value.trim()||!$('courseName').value.trim()){alert('Bitte Name und Kurs schreiben.');return false} localStorage.setItem('dq7_profile',JSON.stringify({name:$('studentName').value.trim(),course:$('courseName').value.trim()}));return true}
function ensureSession(){if(!saveProfile())return false;if(!state.topic)return false;if(!state.session){state.session={version:'7.0-themen-8-aktivitaeten',id:'DQ-'+Date.now(),studentName:$('studentName').value.trim(),courseName:$('courseName').value.trim(),topicId:state.topic.id,topicTitle:state.topic.title,level:state.topic.level,startedAt:nowISO(),startedMs:Date.now(),finishedAt:'',totalSeconds:0,score:0,totalCorrectable:0,activities:[],events:[]}; clearInterval(state.tick); state.tick=setInterval(()=>{$('timer').textContent=fmt(elapsed());$('timer2').textContent=fmt(elapsed())},1000);} return true}
function renderTopics(){const grid=$('topicGrid');grid.innerHTML='';DQ_TOPICS.forEach(t=>{const d=document.createElement('div');d.className='choice-card';d.innerHTML=`<span class="pill">${t.level}</span><h3>${t.title}</h3><p>${t.topic}</p><small>${t.words.length} Wörter</small>`;d.onclick=()=>selectTopic(t.id);grid.appendChild(d)})}
function selectTopic(id){state.topic=DQ_TOPICS.find(t=>t.id===id);state.session=null;ensureSession();$('topicScreen').classList.add('hidden');$('done').classList.add('hidden');showMenu();saveDraft();}
function renderMenu(){const m=$('activityMenu');m.innerHTML='';ACTS.forEach(a=>{const d=document.createElement('div');d.className='choice-card';d.id='menu-'+a.id;d.innerHTML=`<h3>${a.title}</h3><p>${a.desc}</p><small id="done-${a.id}">Noch nicht gespeichert</small>`;d.onclick=()=>openActivity(a.id);m.appendChild(d)})}
function showMenu(){if(!state.topic)return;ensureSession();$('workScreen').classList.add('hidden');$('menuScreen').classList.remove('hidden');$('topicScreen').classList.add('hidden');$('topicLevel').textContent=state.topic.level;$('topicTitle').textContent=state.topic.title;$('topicSub').textContent=state.topic.topic;$('sideTopic').textContent=`${state.topic.level} · ${state.topic.title}`;$('sideActivity').textContent='Aktivität frei wählen.';updateProgress();}
function changeTopic(){state.session=null;state.topic=null;$('menuScreen').classList.add('hidden');$('workScreen').classList.add('hidden');$('topicScreen').classList.remove('hidden');$('sideTopic').textContent='Noch kein Thema gewählt.';updateProgress();}
function openActivity(id){if(!ensureSession())return;state.activity=ACTS.find(a=>a.id===id);state.currentItems=sampleWords();state.activityStart=Date.now();$('menuScreen').classList.add('hidden');$('workScreen').classList.remove('hidden');$('sideActivity').textContent=state.activity.title;renderActivity();saveDraft();}
function renderActivity(){const a=state.activity;const w=state.currentItems;let html=`<div class="activity"><span class="pill">${a.title}</span><h1>${a.desc}</h1>`;
 if(a.id==='flashcards'){html+='<p class="muted">Lies die Karten. Klicke auf Speichern, wenn du sie geübt hast.</p><div class="cards">'+w.map(x=>`<div class="vocab-card"><b>${x.de}</b><span>${x.es}</span><small>${x.example}</small></div>`).join('')+'</div>'}
 if(a.id==='mc-de-es'||a.id==='mc-es-de'){w.forEach((x,i)=>{const q=a.id==='mc-de-es'?x.de:x.es;const ans=a.id==='mc-de-es'?x.es:x.de;const pool=shuffle(state.topic.words.map(y=>a.id==='mc-de-es'?y.es:y.de)).slice(0,3); if(!pool.includes(ans))pool[Math.floor(Math.random()*pool.length)]=ans; html+=`<div class="q"><div class="q-head"><b>${i+1}. ${q}</b><span id="fb-${i}" class="feedback"></span></div><select id="ans-${i}" data-answer="${esc(ans)}"><option value="">Bitte wählen…</option>${shuffle(pool).map(o=>`<option>${esc(o)}</option>`).join('')}</select></div>`})}
 if(a.id==='write-de'||a.id==='write-es'){w.forEach((x,i)=>{const q=a.id==='write-de'?x.es:x.de;const ans=a.id==='write-de'?x.de:x.es;html+=`<div class="q"><div class="q-head"><b>${i+1}. ${q}</b><span id="fb-${i}" class="feedback"></span></div><input id="ans-${i}" data-answer="${esc(ans)}" placeholder="Antwort schreiben…"></div>`})}
 if(a.id==='match'){w.forEach((x,i)=>{const opts=shuffle(w.map(y=>y.es));html+=`<div class="q"><div class="q-head"><b>${i+1}. ${x.de}</b><span id="fb-${i}" class="feedback"></span></div><select id="ans-${i}" data-answer="${esc(x.es)}"><option value="">Bedeutung wählen…</option>${opts.map(o=>`<option>${esc(o)}</option>`).join('')}</select></div>`})}
 if(a.id==='cloze'){w.forEach((x,i)=>{const sentence=x.example.replace(x.de,'_____');html+=`<div class="q"><div class="q-head"><b>${i+1}. ${sentence}</b><span id="fb-${i}" class="feedback"></span></div><input id="ans-${i}" data-answer="${esc(x.de)}" placeholder="Wort ergänzen…"><p class="muted small">Hilfe: ${x.es}</p></div>`})}
 if(a.id==='free'){html+=`<div class="q"><b>Schreibe 5–8 Sätze und verwende mindestens 5 Wörter aus dem Thema.</b><textarea id="freeText" placeholder="Hier schreiben…"></textarea><p class="muted small">Wörter: ${w.map(x=>x.de).join(', ')}</p></div>`}
 html+='</div>';$('activityBox').innerHTML=html;$('workStatus').innerHTML='';}
function check(){if(!state.activity)return;const seconds=Math.max(1,Math.round((Date.now()-state.activityStart)/1000));let rec={activityId:state.activity.id,activityTitle:state.activity.title,type:state.activity.id,timestamp:nowISO(),seconds,items:[],score:0,total:0,freeText:''};
 if(state.activity.id==='flashcards'){rec.items=state.currentItems.map(x=>({question:x.de,response:'gesehen/geübt',answer:x.es,correct:null}));rec.total=0;$('workStatus').innerHTML='<div class="resultbox">Flashcards gespeichert.</div>'}
 else if(state.activity.id==='free'){rec.freeText=$('freeText').value.trim();rec.items.push({question:'Freier Text',response:rec.freeText,answer:'Lehrer prüft',correct:null});$('workStatus').innerHTML='<div class="resultbox">Freier Text vollständig gespeichert.</div>'}
 else{state.currentItems.forEach((x,i)=>{const el=$('ans-'+i);const response=el.value;const answer=el.dataset.answer;const correct=norm(response)===norm(answer);rec.total++; if(correct)rec.score++; rec.items.push({question:questionFor(x),response,answer,correct});$('fb-'+i).innerHTML=correct?'<span class="ok">✓ richtig</span>':`<span class="bad">✗ richtig: ${esc(answer)}</span>`});$('workStatus').innerHTML=`<div class="resultbox">Gespeichert: ${rec.score}/${rec.total} richtig.</div>`}
 state.session.activities=state.session.activities.filter(r=>r.activityId!==rec.activityId);state.session.activities.push(rec);state.session.events.push({type:'activity_saved',activityId:rec.activityId,timestamp:nowISO(),seconds});recalc();saveDraft();updateProgress();if(window.DQ_CONFIG?.SEND_MODE==='checkpoint')send('checkpoint');}
function questionFor(x){const id=state.activity.id;if(id==='mc-de-es'||id==='write-es'||id==='match')return x.de;if(id==='mc-es-de'||id==='write-de')return x.es;if(id==='cloze')return x.example;return x.de}
function recalc(){let score=0,total=0;state.session.activities.forEach(a=>{score+=a.score||0;total+=a.total||0});state.session.score=score;state.session.totalCorrectable=total;state.session.totalSeconds=elapsed()}
function updateProgress(){const done=state.session?state.session.activities.length:0;const pct=Math.round((done/8)*100);$('progressBar').style.width=pct+'%';$('progressText').textContent=`${done}/8 Aktivitäten gespeichert · ${pct}%`;ACTS.forEach(a=>{const el=$('done-'+a.id); if(el)el.textContent=(state.session&&state.session.activities.some(r=>r.activityId===a.id))?'✓ gespeichert':'Noch nicht gespeichert';});}
async function finish(){if(!state.session){alert('Bitte zuerst ein Thema wählen.');return}recalc();state.session.finishedAt=nowISO();state.session.totalSeconds=elapsed();const ok=await send('final');clearInterval(state.tick);$('menuScreen').classList.add('hidden');$('workScreen').classList.add('hidden');$('done').classList.remove('hidden');$('doneText').textContent=ok?'Die komplette Abgabe wurde gesendet.':'Die komplette Abgabe wurde lokal gespeichert. Google-Sheets-URL fehlt oder ist nicht erreichbar.';localStorage.setItem('dq7_last_submission',JSON.stringify(state.session));localStorage.removeItem('dq7_draft')}
async function send(kind){const payload={kind,configProject:window.DQ_CONFIG?.PROJECT_NAME||'DeutschQuest',...state.session};localStorage.setItem('dq7_last_payload',JSON.stringify(payload));const url=window.DQ_CONFIG?.WEBAPP_URL||'';if(!url){$('status').innerHTML='<div class="resultbox warning">Lokal gespeichert. Google-Sheets-URL fehlt in js/config.js.</div>';return false}try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});$('status').innerHTML='<div class="resultbox">✓ An Google Sheets gesendet.</div>';return true}catch(e){$('status').innerHTML='<div class="resultbox warning">Senden nicht möglich. Lokal gespeichert.</div>';return false}}
function saveDraft(){if(state.session)localStorage.setItem('dq7_draft',JSON.stringify({session:state.session,topicId:state.topic?.id}))}
function restoreDraft(){try{const p=JSON.parse(localStorage.getItem('dq7_profile')||'{}');$('studentName').value=p.name||'';$('courseName').value=p.course||'';const d=JSON.parse(localStorage.getItem('dq7_draft')||'null');if(d){state.topic=DQ_TOPICS.find(t=>t.id===d.topicId);state.session=d.session;if(state.topic){$('topicScreen').classList.add('hidden');showMenu();}}}catch(e){}}
function reset(){localStorage.removeItem('dq7_draft');location.reload()}init();
