const $=id=>document.getElementById(id);
const state={lesson:null,idx:0,session:null,tick:null,activityStart:0,checked:{}};
function norm(s){return (s||"").toString().trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[.!?¿¡,;]/g,'').replace(/\s+/g,' ')}
function nowISO(){return new Date().toISOString()}function pad(n){return String(n).padStart(2,'0')}function elapsed(){return state.session?Math.floor((Date.now()-state.session.startedMs)/1000):0}function fmt(sec){return pad(Math.floor(sec/60))+":"+pad(sec%60)}
function init(){DQ_LESSONS.forEach((l,i)=>{let o=document.createElement('option');o.value=l.id;o.textContent=`${l.level} · ${l.title}`;$('lessonSelect').appendChild(o)});$('startBtn').onclick=start;$('resetBtn').onclick=reset;$('prevBtn').onclick=prev;$('nextBtn').onclick=next;$('checkBtn').onclick=checkCurrent;$('finishBtn').onclick=finish;restoreDraft()} 
function start(){const name=$('studentName').value.trim();const course=$('courseName').value.trim();if(!name||!course){alert('Bitte Name und Kurs schreiben.');return}state.lesson=DQ_LESSONS.find(l=>l.id===$('lessonSelect').value);state.idx=0;state.checked={};state.session={version:'7.0',id:'DQ-'+Date.now(),studentName:name,courseName:course,lessonId:state.lesson.id,lessonTitle:state.lesson.title,level:state.lesson.level,startedAt:nowISO(),startedMs:Date.now(),finishedAt:'',totalSeconds:0,score:0,totalCorrectable:0,activities:[],events:[]};$('intro').classList.add('hidden');$('done').classList.add('hidden');$('work').classList.remove('hidden');$('lessonLevel').textContent=state.lesson.level;$('lessonTitle').textContent=state.lesson.title;$('lessonTopic').textContent=state.lesson.topic;clearInterval(state.tick);state.tick=setInterval(()=>{$('timer').textContent=fmt(elapsed())},1000);render();saveDraft()}
function render(){const a=state.lesson.activities[state.idx];state.activityStart=Date.now();$('status').innerHTML='';let html=`<div class="activity"><span class="pill">Aktivität ${state.idx+1}/${state.lesson.activities.length}</span><h2>${a.title}</h2><p class="muted">${a.instruction}</p>`;if(a.type==='mc'){a.items.forEach((it,i)=>{html+=`<div class="q"><div class="q-head"><b>${i+1}. ${it.q}</b><span id="fb-${i}" class="feedback"></span></div><select id="ans-${i}"><option value="">Bitte wählen…</option>${it.options.map(o=>`<option value="${esc(o)}">${o}</option>`).join('')}</select></div>`})}if(a.type==='write'){a.items.forEach((it,i)=>{html+=`<div class="q"><div class="q-head"><b>${i+1}. ${it.q}</b><span id="fb-${i}" class="feedback"></span></div><input id="ans-${i}" placeholder="Antwort schreiben…"></div>`})}if(a.type==='free'){html+=`<div class="q"><b>${a.prompt}</b><textarea id="freeText" placeholder="Hier schreiben…"></textarea><p class="muted small">Freie Texte werden vollständig an den Lehrer gesendet.</p></div>`}html+='</div>';$('activityBox').innerHTML=html;updateProgress()}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function checkCurrent(){const a=state.lesson.activities[state.idx];const seconds=Math.max(1,Math.round((Date.now()-state.activityStart)/1000));let record={activityId:a.id,activityTitle:a.title,type:a.type,activityIndex:state.idx+1,timestamp:nowISO(),seconds,items:[],score:0,total:0,freeText:''};if(a.type==='free'){record.freeText=$('freeText').value.trim();record.items.push({question:a.prompt,response:record.freeText,answer:'Freie Antwort',correct:null,attempt:1});$('status').innerHTML='<div class="resultbox">Freier Text wurde gespeichert.</div>'}else{a.items.forEach((it,i)=>{const val=$('ans-'+i).value;const correct=norm(val)===norm(it.answer);record.total++;if(correct)record.score++;record.items.push({question:it.q,response:val,answer:it.answer,correct,attempt:1});const fb=$('fb-'+i);fb.innerHTML=correct?'<span class="ok">✓ richtig</span>':`<span class="bad">✗ noch einmal üben</span>`});$('status').innerHTML=`<div class="resultbox">Gespeichert: ${record.score}/${record.total} richtig.</div>`}
state.session.activities=state.session.activities.filter(x=>x.activityId!==a.id);state.session.activities.push(record);state.session.events.push({type:'activity_saved',activityId:a.id,timestamp:nowISO(),seconds});recalc();saveDraft();if(window.DQ_CONFIG?.SEND_MODE==='checkpoint')send('checkpoint');updateProgress()}
function recalc(){let score=0,total=0;state.session.activities.forEach(a=>{score+=a.score||0;total+=a.total||0});state.session.score=score;state.session.totalCorrectable=total;state.session.totalSeconds=elapsed()}
function updateProgress(){if(!state.lesson)return;let done=state.session?state.session.activities.length:0;let pct=Math.round((done/state.lesson.activities.length)*100);$('progressBar').style.width=pct+'%';$('progressText').textContent=`${done}/${state.lesson.activities.length} Aktivitäten gespeichert · ${pct}%`}
function next(){if(state.idx<state.lesson.activities.length-1){state.idx++;render()}}function prev(){if(state.idx>0){state.idx--;render()}}
async function finish(){if(!state.session)return;recalc();state.session.finishedAt=nowISO();state.session.totalSeconds=elapsed();const ok=await send('final');clearInterval(state.tick);$('work').classList.add('hidden');$('done').classList.remove('hidden');$('doneText').textContent= ok?'Die komplette Abgabe wurde gesendet.':'Die komplette Abgabe wurde lokal gespeichert. Google-Sheets-URL fehlt oder ist nicht erreichbar.';localStorage.setItem('dq7_last_submission',JSON.stringify(state.session));localStorage.removeItem('dq7_draft')}
async function send(kind){const payload={kind,configProject:window.DQ_CONFIG?.PROJECT_NAME||'DeutschQuest',...state.session};localStorage.setItem('dq7_last_payload',JSON.stringify(payload));const url=window.DQ_CONFIG?.WEBAPP_URL||'';if(!url){$('status').innerHTML='<div class="resultbox warning">Lokal gespeichert. Google-Sheets-URL fehlt in js/config.js.</div>';return false}try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});$('status').innerHTML='<div class="resultbox">✓ An Google Sheets gesendet.</div>';return true}catch(e){$('status').innerHTML='<div class="resultbox warning">Senden nicht möglich. Lokal gespeichert.</div>';return false}}
function saveDraft(){if(state.session)localStorage.setItem('dq7_draft',JSON.stringify({session:state.session,lessonId:state.lesson?.id,idx:state.idx}))}
function restoreDraft(){const raw=localStorage.getItem('dq7_draft');if(!raw)return;try{const d=JSON.parse(raw);$('studentName').value=d.session.studentName||'';$('courseName').value=d.session.courseName||'';$('lessonSelect').value=d.lessonId||DQ_LESSONS[0].id}catch(e){}}
function reset(){localStorage.removeItem('dq7_draft');location.reload()}init();
